### ISSUE TITLE
公式编辑器有几个公式不支持不知道怎么解决,

### ISSUE THREAD

**Issue by heardKing** [handv/react-ueditor-latex#1]
你好, 在这里看到你的项目, 非常感谢你的开源精神. 但是在使用公式编辑器的时候有几个公式不支持不知道作者是怎么解决的呀, 比如向量的表示符等等.

**Comment by handv** [comment]
> 你好, 在这里看到你的项目, 非常感谢你的开源精神. 但是在使用公式编辑器的时候有几个公式不支持不知道作者是怎么解决的呀, 比如向量的表示符等等.

这个是因为ueditor的公式编辑器有很多公式符号是不支持的。所以想要解决的话，就是用latex把公式写出来，然后拷贝到这个ueditor里，就能展示出来。但是要编辑的话，还是得到latex公式编辑器里。
